### ISSUE TITLE
Wont build with yarn

### ISSUE THREAD

**Issue by zdaar** [BringingFire/foundry-module-ts-template#1]
Hi, I was following the steps on the blogpost when I ran into this issue in my codespace.
I ran it locally with the same error.
I decided to clone this repo template and I am still unable to build, so I must be missing something.
Steps : 

yarn install
yarn build

Error is 
```
PS C:\dev\repos\foundry-module-ts-template> yarn build  
yarn run v1.22.19
$ tsc && vite build
undefined
vite v3.2.0 building for production...
The "path" argument must be of type string. Received undefined
error during build:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:116:11)
    at Object.resolve (node:path:167:9)
    at resolve (file:///C:/dev/repos/foundry-module-ts-template/node_modules/vite/dist/node/chunks/dep-61d2428a.js:48161:35)
    at file:///C:/dev/repos/foundry-module-ts-template/node_modules/vite/dist/node/chunks/dep-61d2428a.js:48274:60
    at Array.map (<anonymous>)
    at doBuild (file:///C:/dev/repos/foundry-module-ts-template/node_modules/vite/dist/node/chunks/dep-61d2428a.js:48274:43)
    at async build (file:///C:/dev/repos/foundry-module-ts-template/node_modules/vite/dist/node/chunks/dep-61d2428a.js:48145:16)
    at async CAC.<anonymous> (file:///C:/dev/repos/foundry-module-ts-template/node_modules/vite/dist/node/cli.js:758:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What am I missing ?

**Comment by zdaar** [comment]
The issue lies in vite.config.ts, output.dir is undefined.

**Comment by zdaar** [comment]
There is a problem in the rollupOptions.
I was able to transpile by just using output.dir with output.entryFileNames

**Comment by NunoOliv** [comment]
@zdaar 
Hi. I'm new to rollup and vite. Can you explain your solution or provide a snippet of the file? I'm having trouble getting it to work
Thanks

**Comment by zdaar** [comment]
Hi, you should be able to check the config file in my fork. I’ll take a
look later and give you further help if you need it.

**Comment by NunoOliv** [comment]
Ohh I got it. Separate the file from the directory on the configuration. Makes sense. Its working now. 
Thank you
